### ISSUE TITLE
JSON5 compliance checklist

### ISSUE THREAD

**Issue by dhruvkb** [anchan828/json-ast#650]
Does the package support all features added by JSON5?

## Objects

- [ ] Object keys may be an ECMAScript 5.1 [IdentifierName](https://www.ecma-international.org/ecma-262/5.1/#sec-7.6).
- [ ] Objects may have a single trailing comma.

## Arrays

- [ ] Arrays may have a single trailing comma.

## Strings

- [ ] Strings may be single quoted.
- [ ] Strings may span multiple lines by escaping new line characters.
- [ ] Strings may include character escapes.

## Numbers

- [ ] Numbers may be hexadecimal.
- [ ] Numbers may have a leading or trailing decimal point.
- [ ] Numbers may be [IEEE 754](http://ieeexplore.ieee.org/servlet/opac?punumber=4610933) positive infinity, negative infinity, and NaN.
- [ ] Numbers may begin with an explicit plus sign.

## Comments

- [ ] Single and multi-line comments are allowed.

## White Space

- [ ] Additional white space characters are allowed.

**Comment by anchan828** [comment]
Hi @dhruvkb, I don't know. This is a forked repository, modified to improve performance. I have no plans to provide new features myself.　I probably won't be able to answer your request.

**Comment by dhruvkb** [comment]
@anchan828 since your fork was ~786 commits ahead of the original, I thought it was actively maintained. Sorry!
